
name: CI Workflow

on:
  push:
    branches:
      - main
      - qas
      - develop
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - qas

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, qas, develop]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Rodar testes unitários e integração dependendo da branch
      - name: Run unit tests
        if: matrix.branch == 'develop'
        run: |
          npm install
          npm run test:unit

      - name: Run unit & integration tests
        if: matrix.branch == 'main' || matrix.branch == 'qas'
        run: |
          npm install
          npm run test:unit
          npm run test:integration

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create tag
        run: |
          git config user.name "CI"
          git config user.email "ci@example.com"
          git tag v$(date +'%Y%m%d%H%M%S')
          git push origin --tags
